### ISSUE TITLE
The plugin does not work with Spigot 1.14.1

### ISSUE THREAD

**Issue by uprial** [MCTCP/TerrainControl#576]
Hi,

as far as I understand, the plugin is abandoned.
BTW, I even can pay money if you fix it to the latest server version. :)

Currently, it says with Spigot 1.14.1:

```
[20:35:01] [Server thread/INFO]: [TerrainControl] Enabling TerrainControl v2.9.0-SNAPSHOT
[20:35:01] [Server thread/ERROR]: Error occurred while enabling TerrainControl v2.9.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/MojangsonParseException
	at com.khorn.terraincontrol.bukkit.TXPlugin.onEnable(TXPlugin.java:64) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:195) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.MojangsonParseException
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[?:?]
	... 9 more

```

Thank you!

**Comment by Oct0bass** [comment]
OpenTerrainGenerator is the successor of this plugin / mod.  It is available for 1.12 (and a 1.16 port in the works), and it has more advancd features for preset makers.  It is available for [forge](https://www.curseforge.com/minecraft/mc-mods/openterraingenerator) and [spigot](https://www.spigotmc.org/resources/open-terrain-generator-otg.51373/)
