### ISSUE TITLE
Probleme while create a new world

### ISSUE THREAD

**Issue by cercus** [MCTCP/TerrainControl#491]
Hello, When I create a new world with TerrainControl, with this command : "/mv create farming NORMAL -s 12 -g TerrainControl", there is an error in the console : `21.12 17:00:44 [Server] INFO Starting to enable world ''test''...
21.12 17:00:44 [Server] WARN Failed to get the default chunk generator: java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/World
21.12 17:00:44 [Server] WARN This is a bug in TerrainControl, NOT a bug in Multiverse!
21.12 17:00:44 [Server] INFO Invalid generator! 'TerrainControl'. Aborting world creation.`

I use spigot 1.10.2 and the latest version of this plugin

**Comment by bloodmc** [comment]
TC 1.11 is not going to work with 1.10, use an older build if you want 1.10.2 to work.
