### ISSUE TITLE
Could not set generator for default world

### ISSUE THREAD

**Issue by Pilvinen** [MCTCP/TerrainControl#258]
After updating from TC snapshot 2.5.2 to 2.6.0 released a few days ago I'm getting an error on starting the server (below). 

Don't know what it means nor what to do about it. Reverting back to the old snapshot for now.

I'm using older version of Spigot, 1.7.2.R0.3. Cannot update and test newer builds yet because new versions break one of my more critical plugins.

[11:09:07] [Server thread/INFO]: Preparing level "Aurinkomaa"
[11:09:07] [Server thread/INFO]: [TerrainControl] [INFO] Starting to enable world ''Aurinkomaa''...
[11:09:07] [Server thread/ERROR]: [TerrainControl] Could not set generator for default world 'Aurinkomaa': Plugin 'TerrainControl v2.6.0
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R2/World
        at com.khorn.terraincontrol.bukkit.TCPlugin.getDefaultWorldGenerator(TCPlugin.java:148) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.getGenerator(CraftServer.java:1087) [spigot-1.7.2-R0.3-SNAPSHOT.jar:git-Spigot-1314]
        at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:210) [spigot-1.7.2-R0.3-SNAPSHOT.jar:git-Spigot-1314]
        at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:186) [spigot-1.7.2-R0.3-SNAPSHOT.jar:git-Spigot-1314]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:436) [spigot-1.7.2-R0.3-SNAPSHOT.jar:git-Spigot-1314]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot-1.7.2-R0.3-SNAPSHOT.jar:git-Spigot-1314]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R2.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[spigot-1.7.2-R0.3-SNAPSHOT.jar:git-Spigot-1314]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[spigot-1.7.2-R0.3-SNAPSHOT.jar:git-Spigot-1314]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_51]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_51]
        ... 6 more
